// © 2025 Ali Abu Ras — ali.aburas@deliveryclarity.app. All rights reserved.
// GET /api/backend-view — session-aware import log overview.
// - Authenticated user  → only their own logs
// - Admin               → all users' logs with name and email
// - Unauthenticated     → static endpoint index only, no import data (see
//   2026-07-18 note below)

import { NextRequest, NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { getIronSession } from 'iron-session';
import { SESSION_OPTIONS, type SessionData } from '@/lib/session';
import { prisma } from '@/lib/prisma';

export const dynamic = 'force-dynamic';

// STYLE-09 (2026-07-19, docs/product-audit/10-technical-cleanup.md "3
// hand-maintained API-surface descriptions" finding): this list drifted to
// 17 of the app's 72 real routes before this rewrite, and one entry
// (auth/register) described behavior — "inactive, returns 403" — that was
// no longer true (public self-registration has been live since EP-011).
// Regenerated by walking every app/api/**/route.ts file's real exported HTTP
// methods and leading doc comment. This is a manual, point-in-time
// correction, not a generated/enforced source of truth — the finding's
// underlying "nothing keeps this in sync automatically" risk still stands;
// see the resolution note in 10-technical-cleanup.md for why a generated
// registry was considered and deliberately not built in this pass.
const ENDPOINTS = [
  // ── Auth ──────────────────────────────────────────────────────────────
  { method: 'POST', path: '/api/auth/login',              description: 'Authenticate with email + password — sets session cookie' },
  { method: 'POST', path: '/api/auth/logout',              description: 'Clear session cookie' },
  { method: 'POST', path: '/api/auth/register',            description: 'Public self-registration — creates a user and workspace, rate-limited 5/IP/hour' },
  { method: 'GET',  path: '/api/auth/me',                  description: 'Return the current authenticated user' },
  { method: 'POST', path: '/api/auth/change-password',     description: 'Authenticated password change' },
  { method: 'POST', path: '/api/auth/forgot-password',     description: 'Public, rate-limited password reset request' },
  { method: 'POST', path: '/api/auth/reset-password',      description: 'Consume a reset token and set a new password' },
  { method: 'POST', path: '/api/auth/verify-email',        description: 'Consume a verification token and mark email verified' },
  { method: 'POST', path: '/api/auth/resend-verification', description: 'Send a fresh email verification link' },
  // ── Account & profile ────────────────────────────────────────────────
  { method: 'GET/PATCH',       path: '/api/profile',                     description: 'Read or update the current user profile' },
  { method: 'GET/POST',        path: '/api/profile/image',               description: 'Upload or stream S3-backed profile images under images/profile/' },
  { method: 'GET/PUT/DELETE',  path: '/api/profile/storage-provider',    description: "Manage the caller's own 'bring your own cloud' storage config" },
  { method: 'POST',            path: '/api/profile/storage-provider/test', description: "Test the caller's saved cloud storage provider connection" },
  { method: 'GET',             path: '/api/members',                    description: 'Authenticated team member directory' },
  { method: 'GET',             path: '/api/entitlement',                description: "Return the current user's trial entitlement state" },
  { method: 'GET',             path: '/api/user-add-requests/mine',     description: "Return the current user's own submitted add-member requests" },
  { method: 'POST',            path: '/api/user-add-requests',          description: 'Submit a request to add a new member' },
  // ── Upload & import data ─────────────────────────────────────────────
  { method: 'POST',   path: '/api/upload',          description: 'Upload a Jira CSV or Excel file and trigger import processing' },
  { method: 'POST',   path: '/api/upload/merge',    description: 'Merge up to 10 Jira exports into one unified report' },
  { method: 'GET',    path: '/api/imports',         description: 'List import logs for the current user (admin: ?all=true for all)' },
  { method: 'GET',    path: '/api/imports/export',  description: "Download the caller's import logs (admin: ?all=true for all) as an Excel workbook" },
  { method: 'DELETE', path: '/api/imports/:id',     description: "Delete a specific import log (own, or any as admin)" },
  { method: 'DELETE', path: '/api/imports/all',     description: 'Delete all import logs for the current user (admin: ?userId= for any user)' },
  { method: 'POST',   path: '/api/jira/sync',       description: "Manually sync the current user's connected Jira instance" },
  { method: 'POST',   path: '/api/retro/parse',     description: 'Parse an uploaded retro file (CSV/XLSX/XLS/Markdown/text) and return a preview' },
  // ── Dashboard data ────────────────────────────────────────────────────
  { method: 'GET',          path: '/api/metrics',          description: 'Return whether a successful import exists and its timestamp' },
  { method: 'GET',          path: '/api/metrics/latest',   description: 'Load the latest dashboard metrics from cloud-backed server storage' },
  { method: 'GET',          path: '/api/trends',           description: 'Return upload-over-upload history with metrics for trend analysis' },
  { method: 'GET/POST',     path: '/api/snapshots',        description: "List or save the current user's dashboard snapshots" },
  { method: 'GET/DELETE',   path: '/api/snapshots/:id',    description: 'Load or delete a specific dashboard snapshot (own, or any as admin)' },
  { method: 'GET',          path: '/api/notifications',    description: 'List notifications for the current user, newest first' },
  { method: 'PATCH',        path: '/api/notifications/:id/read', description: 'Mark a notification as read' },
  // ── Meta / status ─────────────────────────────────────────────────────
  { method: 'GET',  path: '/api/dashboard',      description: 'Static status/service-metadata stub — no live metrics (name is legacy)' },
  { method: 'GET',  path: '/api/health',         description: 'Health check — confirms the API service is running' },
  { method: 'GET',  path: '/api/ready',          description: 'Readiness probe — checks database connectivity, used by deployment health checks' },
  { method: 'GET',  path: '/api/backend-view',   description: 'JSON overview of import stats, recent logs, and this API endpoint index' },
  { method: 'GET',  path: '/api/developer-view', description: 'Architecture, service, and health-scoring reference for contributors (auth required)' },
  { method: 'GET',  path: '/api/docs',           description: 'Serve an allow-listed internal product-documentation file (e.g. ?doc=srs)' },
  { method: 'POST', path: '/api/demo-request',   description: 'Public "Request a demo" lead-capture form on /promo' },
  { method: 'POST', path: '/api/events/error',   description: 'Receive a client-side error report from the browser' },
  { method: 'POST', path: '/api/feedback',       description: 'Capture structured user feedback (auth optional)' },
  // ── Admin ─────────────────────────────────────────────────────────────
  { method: 'GET/POST/PATCH/DELETE', path: '/api/admin/users',                       description: 'Admin-only user management' },
  { method: 'GET',                   path: '/api/admin/users/:id/reset-preview',     description: "Dry-run preview of a user's workspace-data reset (admin only)" },
  { method: 'POST',                  path: '/api/admin/users/:id/reset',             description: "Delete a user's workspace data — import logs, snapshots (admin only)" },
  { method: 'GET',                   path: '/api/admin/user-add-requests',           description: 'List all pending user-add requests (admin only)' },
  { method: 'PATCH',                 path: '/api/admin/user-add-requests/:id/accept', description: 'Accept a request to add a new member (admin only)' },
  { method: 'PATCH',                 path: '/api/admin/user-add-requests/:id/reject', description: 'Reject a request to add a new member (admin only)' },
  { method: 'GET/PUT/POST',          path: '/api/admin/app-config',                  description: 'Read (GET) or save (PUT) app config, or ?action=test/test-jira to send a test (admin only)' },
  { method: 'GET',                   path: '/api/admin/audit-events',                description: 'Paginated audit event log (admin only)' },
  { method: 'GET',                   path: '/api/admin/audit-events/stats',          description: 'Audit-log chart data — totals, events-per-day, event types (admin only)' },
  { method: 'GET',                   path: '/api/admin/feedback',                    description: 'Paginated feedback list for admin triage' },
  { method: 'PATCH',                 path: '/api/admin/feedback/:id',                description: 'Update feedback status and an optional note (admin only)' },
  { method: 'GET',                   path: '/api/admin/diagnostics',                 description: 'System health snapshot (admin only)' },
  { method: 'GET',                   path: '/api/admin/security',                    description: 'Run security checks and return a report (admin only)' },
  { method: 'GET',                   path: '/api/admin/backup',                      description: 'Create/download a backup bundle, or ?info=true for size only (admin only)' },
  { method: 'POST',                  path: '/api/admin/restore',                     description: 'Restore from a backup bundle JSON file (admin only)' },
  { method: 'POST',                  path: '/api/admin/cleanup',                     description: 'Trigger manual retention cleanup, or ?action=clear_all to wipe all data (admin only)' },
  { method: 'GET/POST',              path: '/api/admin/settings',                    description: 'Read or update data-retention settings (admin only)' },
  { method: 'GET/POST',              path: '/api/admin/storage',                     description: 'Read or update the active cloud storage provider/credentials (admin only)' },
  { method: 'GET/POST',              path: '/api/admin/storage/sync',                description: 'Check sync status, or trigger a cloud sync/push (admin only)' },
  { method: 'GET/POST',              path: '/api/admin/storage/auto-restore',        description: 'Check local DB health, or trigger auto-restore from cloud (admin only)' },
  { method: 'GET',                   path: '/api/admin/storage/download',            description: 'Download a backup file from the active cloud provider (admin only)' },
  { method: 'GET/POST',              path: '/api/admin/jira-connections',            description: 'List or create Jira API connections (admin only)' },
  { method: 'DELETE',                path: '/api/admin/jira-connections/:id',        description: 'Remove a Jira API connection (admin only)' },
  { method: 'POST',                  path: '/api/admin/jira-connections/:id/test',   description: "Verify a Jira connection's credentials work (admin only)" },
  { method: 'POST',                  path: '/api/admin/jira-connections/:id/sync',   description: 'Manually sync one Jira connection (admin only)' },
  { method: 'GET',                   path: '/api/admin/jira-connections/:id/fields', description: "Discover a Jira instance's field ID → name mapping (admin only)" },
  { method: 'GET/POST',              path: '/api/admin/orphan-rules',                description: 'Read (any user) or update (admin) orphan-issue detection rules' },
  { method: 'GET/POST',              path: '/api/admin/thresholds',                  description: 'Read (any user) or update (admin) health-score thresholds' },
  { method: 'GET/POST',              path: '/api/admin/issue-type-hierarchy',        description: "Read (any user) or update (admin) this user's issue-type hierarchy config" },
  { method: 'GET/POST',              path: '/api/admin/persona-preview',             description: 'Read, or toggle (super-admin only), the soft-launch persona switcher' },
  { method: 'GET/POST/PATCH',        path: '/api/admin/system-errors',               description: 'List system error logs, retry an operation, or mark one resolved (admin only)' },
];

export async function GET(req: NextRequest): Promise<NextResponse> {
  // ── Session-aware DB path ─────────────────────────────────────────────────
  try {
    const session = await getIronSession<SessionData>(cookies(), SESSION_OPTIONS);

    if (session.isLoggedIn) {
      const isAdmin = session.role === 'admin';

      const dbLogs = await prisma.importLog.findMany({
        where:   isAdmin ? {} : { userId: session.userId },
        include: { user: { select: { name: true, email: true } } },
        orderBy: { uploadedAt: 'desc' },
        take:    50,
      });

      const total      = dbLogs.length;
      const successful = dbLogs.filter(l => l.status === 'success').length;
      const failed     = dbLogs.filter(l => ['failed', 'validation_failed'].includes(l.status)).length;
      const last       = dbLogs[0] ?? null;

      const stats = {
        totalImports:      total,
        successfulImports: successful,
        failedImports:     failed,
        lastImport:        last?.uploadedAt?.toISOString() ?? null,
        lastFilename:      last?.fileName ?? null,
        lastRowCount:      last?.rowCount ?? null,
      };

      const logs = dbLogs.map(l => ({
        id:          l.id,
        timestamp:   l.uploadedAt?.toISOString() ?? null,
        filename:    l.fileName,
        rowCount:    l.rowCount,
        status:      l.status,
        filesize:    l.fileSize,
        healthScore: l.healthScore,
        totalIssues: l.totalIssues,
        // Only expose user identity to admins
        userName:    isAdmin ? (l.user?.name  ?? 'Unknown') : null,
        userEmail:   isAdmin ? (l.user?.email ?? '')        : null,
      }));

      return NextResponse.json({
        stats, logs, endpoints: ENDPOINTS,
        isAdmin, currentUser: { name: session.name, email: session.email, role: session.role },
      });
    }
  } catch {
    // Prisma unavailable or session error — fall through
  }

  // ── Fallback: unauthenticated — static endpoint index only ────────────────
  //
  // SEC (2026-07-18, docs/product-audit/10-technical-cleanup.md Part 1
  // finding 2): this used to call readImportLogs(), reading
  // data/import-logs.json — the SAME single flat file, shared globally by
  // every user with no per-user scoping whatsoever, that GET /api/imports'
  // 2026-07-08 P0 fix (see that route's own comment) removed entirely from
  // ITS unauthenticated path for exactly this reason: "no legitimate case
  // where this route should ever answer without a valid session or with
  // unscoped data." That file is still actively written on every upload
  // (app/api/upload/route.ts's appendImportLog() call) — so this fallback
  // was serving real cross-account filenames, row counts, statuses, and file
  // sizes to any unauthenticated caller, unlike the route's own doc comment
  // claimed ("no user data"): userName/userEmail were nulled out, but
  // filename/rowCount/status/filesize were not, and a filename alone can be
  // sensitive (client/project names, confidential markers). Unlike
  // /api/imports, this route's whole purpose also includes doubling as a
  // public, unauthenticated API index (see the "endpoints" list returned
  // below and its inclusion in PUBLIC_API in middleware.ts), so the fix here
  // is narrower than that route's outright 401: keep the endpoint index
  // public, drop the real import data instead of substituting a different
  // unscoped source.
  return NextResponse.json({
    stats: {
      totalImports: null, successfulImports: null, failedImports: null,
      lastImport: null, lastFilename: null, lastRowCount: null,
    },
    logs: [],
    endpoints: ENDPOINTS,
    isAdmin: false,
    currentUser: null,
  });
}
